services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dynamic-wallpapers
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    vite:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_vite
        command: sh -c "npm install && npm run dev"
        volumes:
            - .:/var/www
        ports:
            - "5173:5173"
        networks:
            - laravel
        environment:
            VITE_HOST: 0.0.0.0

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
